fragment EventFragment on EventRecord {
	__typename
	_createdAt
	id
	title
	subtitle
	introHeadline
	intro {
		value
		blocks
	}
	content {
		value
		blocks {
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
			}
		}
	}
	image {
		...ImageFragment
	}
	gallery {
		...GalleryFragment
	}
	video {
		...VideoFragment
	}
	videoImage {
		...ImageFragment
	}
	videoCaption
	metaInfo {
		__typename
		id
		headline
		text {
			__typename
			blocks
			value
		}
	}
	cv {
		__typename
		id
		headline
		text {
			__typename
			blocks
			value
		}
	}
	slug
	_allSlugLocales {
		locale
		value
	}
}
