query Anniversary($locale: SiteLocale!) {
	anniversary(locale: $locale) {
		id
		title
		intro {
			value
			blocks
		}
		content {
			value
			blocks
		}
	}
}

query AllAnniversaryPages($locale: SiteLocale!) {
	anniversaryPages: allAnniversaryPages(locale: $locale, first: 100) {
		...AnniversaryPageFragment
	}
}

query AnniversaryPage($slug: String!, $locale: SiteLocale) {
	anniversaryPage(filter: { slug: { eq: $slug } }, locale: $locale) {
		...AnniversaryPageFragment
	}
}
