query AllArchives($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale = en) {
	allArchives(first: $first, skip: $skip, locale: $locale, orderBy: _createdAt_DESC) {
		...ArchiveFragmentLight
	}
	_allArchivesMeta(locale: $locale) {
		count
	}
}

query Archive($slug: String!, $locale: SiteLocale = en) {
	archive(filter: { slug: { eq: $slug } }, locale: $locale) {
		...ArchiveFragment
	}
}

query ArchiveIntro($locale: SiteLocale) {
	archiveIntro(locale: $locale) {
		title
		text {
			value
			blocks
		}
	}
}

fragment ArchiveFragment on ArchiveRecord {
	__typename
	_createdAt
	id
	title
	content {
		value
		blocks {
			__typename
			id
			... on ImageRecord {
				__typename
				image {
					...ImageFragment
				}
				layout
			}
		}
	}
	slug
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment ArchiveFragmentLight on ArchiveRecord {
	__typename
	_createdAt
	id
	title
	slug
}
