query Contact($locale: SiteLocale) {
	contact(locale: $locale) {
		image {
			...ImageFragment
		}
		mailingAddress
		email
		instagram
		people {
			...PersonFragment
		}
	}
}

fragment PersonFragment on PersonRecord {
	__typename
	id
	firstName
	lastName
	email
	location
	phone
	role
}
