query AllEvents($first: IntType = 100, $skip: IntType = 0, $locale: SiteLocale) {
	events: allEvents(locale: $locale, first: $first, skip: $skip, orderBy: _createdAt_ASC) {
		...EventFragmentLight
	}
	pagination: _allEventsMeta {
		count
	}
}

query Event($slug: String!, $locale: SiteLocale) {
	event(filter: { slug: { eq: $slug } }, locale: $locale) {
		...EventFragment
	}
}
