query Start($locale: SiteLocale) {
	start(locale: $locale) {
		id
		content {
			... on StartImageRecord {
				id
				layout
				image {
					...ImageFragment
				}
				title
				section
				text(markdown: false)
				link {
					... on InternalLinkRecord {
						__typename
						title
						record {
							... on EventRecord {
								...EventFragmentLight
							}
							... on ProjectRecord {
								...ProjectFragmentLight
							}
							... on ArchiveRecord {
								...ArchiveFragmentLight
							}
						}
					}
					... on ExternalLinkRecord {
						__typename
						title
						url
					}
				}
			}
			... on StartImagesDoubleRecord {
				id
				images {
					image {
						...ImageFragment
					}
					title
					section
					text(markdown: false)
					link {
						... on InternalLinkRecord {
							__typename
							title
							record {
								... on EventRecord {
									...EventFragmentLight
								}
								... on ProjectRecord {
									...ProjectFragmentLight
								}
								... on ArchiveRecord {
									...ArchiveFragmentLight
								}
							}
						}
						... on ExternalLinkRecord {
							__typename
							title
							url
						}
					}
				}
			}
			... on StartTextRecord {
				id
				title
				layout
				section
				text(markdown: false)
			}
		}
	}
}
